name: E2E against Production

on:
  pull_request:
  workflow_dispatch:

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20      # keep your Node version
          # remove: cache: 'npm' (needs a lockfile)

      - name: Install deps
        run: npm install        # <-- not `npm ci`

      - name: Verify Cypress
        run: npx cypress verify

      - name: Run Cypress (prod)
        env:
          CYPRESS_BASE_URL: https://comp-30022-group-30-mental-health-s.vercel.app
        run: npx cypress run --spec "cypress/e2e/home.smoke.cy.ts,cypress/e2e/llm_search.smoke.cy.ts"

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
